<?php
defined( 'ABSPATH' ) || exit;

/**
* You can edit this file, but it will be overwritten in the next update,
* this file is autogenerated depending on your account
* or you can define these values directly in your wp-config.php file
*/

// Your license KEY.
if ( ! defined( 'WP_SWAPPER_KEY' ) ) {
    define( 'WP_SWAPPER_KEY', '' );
}

// Your email, the one used for the purchase
if ( ! defined('WP_SWAPPER_EMAIL') ) {
    define( 'WP_SWAPPER_EMAIL', '' );
}
